<gwf_interface>
	Label:
		text: "Model Name"
		size_hint: (0.2,0.1)
		pos_hint: {"x": 0,'y':0.9}
	TextInput:
		size_hint: (0.2,0.1)
		pos_hint: {"x": 0.2,'y':0.9}
	Label:
		size_hint:(0.2,0.1)
		pos_hint: {"x": 0,'y':0.8}
		text: "Newton Options"

	TextInput:
		id: newton_options
		size_hint:(0.2,0.1)
		pos_hint: {"x": 0.2,'y':0.8}

	Button:
		text: "create"
		pos_hint: {"center_x": 0.5,'center_y':0.1}
		on_release: root.generate_bc()

