<gwfnpf_interface>
	Label:
		text: 'Hydraulic conductivity'
		size_hint: (0.3,0.05)
		pos_hint: {"center_x": 0.2,'y':0.9}

	Label:
		size_hint:(0.3,0.05)
		pos_hint: {"center_x": 0.5,'y':0.9}
		text: "Aquifer type"

	ScrollView:
		size_hint: (1, 0.85)
		pos_hint: {"x": 0,'y':0.1}
		do_scroll_x: False
        do_scroll_y: True
		BoxLayout:
			size_hint: None,None
			size: root.width, root.height*5
			id: npf_box
			orientation: "vertical"

